# using the node js 18 image wiht alpine linux

FROM node:18-alpine

WORKDIR /user/src/app

COPY package*.json ./

RUN npm ci --only=production

COPY  . .

EXPOSE 3001

CMD [ "node" , "src/server.js" ]